[package]
name = "cs2external"
version = "0.0.1"
authors = ["Vytrol", "TKazer"]
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
colored = "2.0.4"
dont_disappear = "3.0.1"
imgui = "0.11.0"
imgui-winit-support = "0.11.0"
glium = { version = "0.32.1", features = ["glutin"] }
imgui-glium-renderer = "0.11.0"
rdev = "0.5.3"
mint = "0.5.9"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
directories = "5.0.1"
windows = { version = "0.51.1", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_Graphics_Gdi", "Win32_System_Threading", "Win32_System_Diagnostics_Debug", "Win32_System_Memory", "Win32_System_Diagnostics_ToolHelp"] }
mouse-rs = "0.4.2"
