name: Build and deploy software
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      - name: Build application
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-msvc --target-dir ./build
      - name: Move executable
        run: |
          mkdir ./bin 2>nul
          move ./build/x86_64-pc-windows-msvc/release/proext.exe ./bin
      - name: Save hash
        run: |
          $(CertUtil -hashfile ./bin/proext.exe MD5)[1] -replace " ","" > ./bin/hash.txt
      - name: Commit and push
        run: |
          git config --global user.name "Vytrol"
          git config --global user.email "63375371+vytrol@users.noreply.github.com"
          git add ./bin
          git commit -m "📦 Updated Binaries"
          git push